# Generated by Django 4.0.3 on 2022-04-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_bank_bank_users_user_banks_alter_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit_status',
            field=models.CharField(choices=[('denied', 'denied'), ('checking', 'checking'), ('accepted', 'accepted')], default='checking', max_length=200),
        ),
        migrations.AddField(
            model_name='installment',
            name='installment_status',
            field=models.CharField(choices=[('denied', 'denied'), ('checking', 'checking'), ('accepted', 'accepted')], default='checking', max_length=200),
        ),
    ]
