# Generated by Django 4.0.3 on 2022-04-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_remove_account_freeze_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeze_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='freeze_status',
        ),
    ]
