# Generated by Django 4.0.3 on 2022-04-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_economics_remove_user_freeze_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='economics',
            options={'verbose_name_plural': 'economics'},
        ),
    ]
